[2025-02-27T19:55:45.927+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/sqlalchemy.py:124 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-02-27T19:55:45.945+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: coingecko_ingestion_dag.run_mapreduce_job scheduled__2025-02-26T00:00:00+00:00 [queued]>
[2025-02-27T19:55:45.960+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: coingecko_ingestion_dag.run_mapreduce_job scheduled__2025-02-26T00:00:00+00:00 [queued]>
[2025-02-27T19:55:45.961+0000] {taskinstance.py:1361} INFO - Starting attempt 2 of 2
[2025-02-27T19:55:45.979+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): run_mapreduce_job> on 2025-02-26 00:00:00+00:00
[2025-02-27T19:55:45.984+0000] {standard_task_runner.py:57} INFO - Started process 285 to run task
[2025-02-27T19:55:45.989+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'coingecko_ingestion_dag', 'run_mapreduce_job', 'scheduled__2025-02-26T00:00:00+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/coingecko_pipeline.py', '--cfg-path', '/tmp/tmpwmxrl0kr']
[2025-02-27T19:55:45.993+0000] {standard_task_runner.py:85} INFO - Job 5: Subtask run_mapreduce_job
[2025-02-27T19:55:46.010+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-02-27T19:55:46.051+0000] {task_command.py:415} INFO - Running <TaskInstance: coingecko_ingestion_dag.run_mapreduce_job scheduled__2025-02-26T00:00:00+00:00 [running]> on host 66b504a65b04
[2025-02-27T19:55:46.069+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/sqlalchemy.py:124 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-02-27T19:55:46.187+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='etudiant' AIRFLOW_CTX_DAG_ID='coingecko_ingestion_dag' AIRFLOW_CTX_TASK_ID='run_mapreduce_job' AIRFLOW_CTX_EXECUTION_DATE='2025-02-26T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-02-26T00:00:00+00:00'
[2025-02-27T19:55:46.189+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-02-27T19:55:46.191+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', '\n        docker exec -i namenode bash -c "\n      hadoop jar /opt/hadoop-3.2.1/share/hadoop/tools/lib/hadoop-streaming-3.2.1.jar    -files /tmp/mapper.py,/tmp/reducer.py    -input /user/etudiant/crypto/raw/YYYY=2025/MM=02/DD=26/coingecko_raw.json    -output /user/etudiant/crypto/processed/YYYY=2025/MM=02/DD=26    -mapper mapper.py    -reducer reducer.py\n    ']
[2025-02-27T19:55:46.211+0000] {subprocess.py:86} INFO - Output:
[2025-02-27T19:55:46.215+0000] {subprocess.py:93} INFO - /bin/bash: -c: line 2: unexpected EOF while looking for matching `"'
[2025-02-27T19:55:46.216+0000] {subprocess.py:93} INFO - /bin/bash: -c: line 5: syntax error: unexpected end of file
[2025-02-27T19:55:46.216+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2025-02-27T19:55:46.227+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2025-02-27T19:55:46.231+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=coingecko_ingestion_dag, task_id=run_mapreduce_job, execution_date=20250226T000000, start_date=20250227T195545, end_date=20250227T195546
[2025-02-27T19:55:46.245+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 5 for task run_mapreduce_job (Bash command failed. The command returned a non-zero exit code 2.; 285)
[2025-02-27T19:55:46.291+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-02-27T19:55:46.308+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-27T20:43:06.552+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/sqlalchemy.py:124 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-02-27T20:43:06.563+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: coingecko_ingestion_dag.run_mapreduce_job scheduled__2025-02-26T00:00:00+00:00 [queued]>
[2025-02-27T20:43:06.572+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: coingecko_ingestion_dag.run_mapreduce_job scheduled__2025-02-26T00:00:00+00:00 [queued]>
[2025-02-27T20:43:06.572+0000] {taskinstance.py:1361} INFO - Starting attempt 2 of 2
[2025-02-27T20:43:06.585+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): run_mapreduce_job> on 2025-02-26 00:00:00+00:00
[2025-02-27T20:43:06.589+0000] {standard_task_runner.py:57} INFO - Started process 285 to run task
[2025-02-27T20:43:06.592+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'coingecko_ingestion_dag', 'run_mapreduce_job', 'scheduled__2025-02-26T00:00:00+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/coingecko_pipeline.py', '--cfg-path', '/tmp/tmpyqxsjmpq']
[2025-02-27T20:43:06.594+0000] {standard_task_runner.py:85} INFO - Job 5: Subtask run_mapreduce_job
[2025-02-27T20:43:06.608+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-02-27T20:43:06.639+0000] {task_command.py:415} INFO - Running <TaskInstance: coingecko_ingestion_dag.run_mapreduce_job scheduled__2025-02-26T00:00:00+00:00 [running]> on host 3c576f746ebe
[2025-02-27T20:43:06.649+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/sqlalchemy.py:124 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-02-27T20:43:06.701+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='etudiant' AIRFLOW_CTX_DAG_ID='coingecko_ingestion_dag' AIRFLOW_CTX_TASK_ID='run_mapreduce_job' AIRFLOW_CTX_EXECUTION_DATE='2025-02-26T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-02-26T00:00:00+00:00'
[2025-02-27T20:43:06.703+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-02-27T20:43:06.703+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', '\n        docker exec -i namenode bash -c "\n      hadoop jar /opt/hadoop-3.2.1/share/hadoop/tools/lib/hadoop-streaming-3.2.1.jar    -files /tmp/mapper.py,/tmp/reducer.py    -input /user/etudiant/crypto/raw/YYYY=2025/MM=02/DD=26/coingecko_raw.json    -output /user/etudiant/crypto/processed/YYYY=2025/MM=02/DD=26    -mapper mapper.py    -reducer reducer.py\n    ']
[2025-02-27T20:43:06.711+0000] {subprocess.py:86} INFO - Output:
[2025-02-27T20:43:06.713+0000] {subprocess.py:93} INFO - /bin/bash: -c: line 2: unexpected EOF while looking for matching `"'
[2025-02-27T20:43:06.714+0000] {subprocess.py:93} INFO - /bin/bash: -c: line 5: syntax error: unexpected end of file
[2025-02-27T20:43:06.714+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2025-02-27T20:43:06.723+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2025-02-27T20:43:06.726+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=coingecko_ingestion_dag, task_id=run_mapreduce_job, execution_date=20250226T000000, start_date=20250227T204306, end_date=20250227T204306
[2025-02-27T20:43:06.735+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 5 for task run_mapreduce_job (Bash command failed. The command returned a non-zero exit code 2.; 285)
[2025-02-27T20:43:06.773+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-02-27T20:43:06.794+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-27T22:21:46.986+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/sqlalchemy.py:124 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-02-27T22:21:46.996+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: coingecko_ingestion_dag.run_mapreduce_job scheduled__2025-02-26T00:00:00+00:00 [queued]>
[2025-02-27T22:21:47.005+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: coingecko_ingestion_dag.run_mapreduce_job scheduled__2025-02-26T00:00:00+00:00 [queued]>
[2025-02-27T22:21:47.005+0000] {taskinstance.py:1361} INFO - Starting attempt 2 of 2
[2025-02-27T22:21:47.016+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): run_mapreduce_job> on 2025-02-26 00:00:00+00:00
[2025-02-27T22:21:47.021+0000] {standard_task_runner.py:57} INFO - Started process 419 to run task
[2025-02-27T22:21:47.024+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'coingecko_ingestion_dag', 'run_mapreduce_job', 'scheduled__2025-02-26T00:00:00+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/coingecko_pipeline.py', '--cfg-path', '/tmp/tmp6oifbud8']
[2025-02-27T22:21:47.027+0000] {standard_task_runner.py:85} INFO - Job 5: Subtask run_mapreduce_job
[2025-02-27T22:21:47.042+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-02-27T22:21:47.071+0000] {task_command.py:415} INFO - Running <TaskInstance: coingecko_ingestion_dag.run_mapreduce_job scheduled__2025-02-26T00:00:00+00:00 [running]> on host 2d549a908a24
[2025-02-27T22:21:47.083+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/sqlalchemy.py:124 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-02-27T22:21:47.158+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='etudiant' AIRFLOW_CTX_DAG_ID='coingecko_ingestion_dag' AIRFLOW_CTX_TASK_ID='run_mapreduce_job' AIRFLOW_CTX_EXECUTION_DATE='2025-02-26T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-02-26T00:00:00+00:00'
[2025-02-27T22:21:47.160+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-02-27T22:21:47.160+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', '\n            docker exec -i namenode bash -c "\n        hadoop jar /opt/hadoop-3.2.1/share/hadoop/tools/lib/hadoop-streaming-3.2.1.jar    -files /tmp/mapper.py,/tmp/reducer.py    -input /user/etudiant/crypto/raw/YYYY=2025/MM=02/DD=26/coingecko_raw.json    -output /user/etudiant/crypto/processed/YYYY=2025/MM=02/DD=26    -mapper mapper.py    -reducer reducer.py"\n        ']
[2025-02-27T22:21:47.174+0000] {subprocess.py:86} INFO - Output:
[2025-02-27T22:21:48.853+0000] {subprocess.py:93} INFO - 2025-02-27 22:21:48,852 INFO impl.MetricsConfig: Loaded properties from hadoop-metrics2.properties
[2025-02-27T22:21:48.925+0000] {subprocess.py:93} INFO - 2025-02-27 22:21:48,924 INFO impl.MetricsSystemImpl: Scheduled Metric snapshot period at 10 second(s).
[2025-02-27T22:21:48.926+0000] {subprocess.py:93} INFO - 2025-02-27 22:21:48,924 INFO impl.MetricsSystemImpl: JobTracker metrics system started
[2025-02-27T22:21:48.942+0000] {subprocess.py:93} INFO - 2025-02-27 22:21:48,941 WARN impl.MetricsSystemImpl: JobTracker metrics system already initialized!
[2025-02-27T22:21:49.045+0000] {subprocess.py:93} INFO - 2025-02-27 22:21:49,044 ERROR streaming.StreamJob: Error Launching job : Output directory hdfs://namenode:9000/user/etudiant/crypto/processed/YYYY=2025/MM=02/DD=26 already exists
[2025-02-27T22:21:49.046+0000] {subprocess.py:93} INFO - Streaming Command Failed!
[2025-02-27T22:21:49.531+0000] {subprocess.py:97} INFO - Command exited with return code 5
[2025-02-27T22:21:49.541+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 5.
[2025-02-27T22:21:49.545+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=coingecko_ingestion_dag, task_id=run_mapreduce_job, execution_date=20250226T000000, start_date=20250227T222146, end_date=20250227T222149
[2025-02-27T22:21:49.555+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 5 for task run_mapreduce_job (Bash command failed. The command returned a non-zero exit code 5.; 419)
[2025-02-27T22:21:49.582+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-02-27T22:21:49.599+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
